name: CI Pipeline

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js (for example)
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: cd github npm install

    - name: Run tests
      run: npm test
